### PR TITLE
Set maps maxBounds

### PR DESCRIPTION
**Pull request by ghost**
...so the user won't get lost in the map accidentally when scrolling.

### CODE REVIEW

**Comment by covid19cubadata** [comment]
I think it is already fixed. If it isnt reopen. Thanks!

**Comment by ghost** [comment]
It is not. If you drag the map you can easily go off the Cuba bounds thus getting an empty map.
And thank you for all the effort!

**Comment by ghost** [comment]
This fix makes the map bounce back to Cuba if you try to move/drag the map off Cuba

**Comment by ghost** [comment]
Fixes #30

**Comment by covid19cubadata** [comment]
Already fixed. Idea was included on code! Thanks.

**Pull request closed without merging**
